import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { NextResponse } from "next/server";
import { checkClientLimit } from "@/lib/usage";

// POST /api/intake - Generate a new intake questionnaire link
export async function POST() {
  const supabase = await createClient();

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Check client limit before generating link
  const clientLimit = await checkClientLimit(user.id);
  if (!clientLimit.allowed) {
    return NextResponse.json(
      {
        error: "Client limit reached",
        message: `You've reached your limit of ${clientLimit.limit} clients. Upgrade to add more.`,
        showUpgrade: true,
      },
      { status: 403 }
    );
  }

  // Insert intake link using admin client (token generated by DB default)
  const admin = createAdminClient();
  const { data, error } = await admin
    .from("intake_links")
    .insert({ user_id: user.id })
    .select("token, expires_at")
    .single();

  if (error) {
    console.error("Error creating intake link:", error);
    return NextResponse.json(
      { error: "Failed to generate questionnaire link" },
      { status: 500 }
    );
  }

  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://retirementexpert.ai";
  const url = `${baseUrl}/intake/${data.token}`;

  return NextResponse.json(
    { token: data.token, url, expires_at: data.expires_at },
    { status: 201 }
  );
}
