import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { NextRequest, NextResponse } from "next/server";
import { checkClientLimit } from "@/lib/usage";

// Far-future date for permanent links so the existing NOT NULL +
// "expired"-status logic stays coherent without special-casing nullability.
const PERMANENT_LINK_EXPIRY_ISO = new Date(
  Date.now() + 100 * 365 * 24 * 60 * 60 * 1000
).toISOString();

// POST /api/intake - Generate a new intake questionnaire link.
// Body: { permanent?: boolean } — when true, the link is reusable forever
// (each submission creates a new client) and intended for advisor websites.
// Default (false) keeps the legacy single-use, 7-day-expiry behavior used
// for one-off client invitations.
export async function POST(request: NextRequest) {
  const supabase = await createClient();

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();

  if (authError || !user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Body is optional — POSTs from the legacy modal send no body at all.
  let permanent = false;
  try {
    const body = await request.json();
    permanent = body?.permanent === true;
  } catch {
    // No body / not JSON — fall through with the single-use default.
  }

  // Check client limit before generating link. For permanent links we still
  // gate at generation time so an over-limit advisor can't seed a reusable
  // URL; per-submission re-checks below catch the case where they hit the
  // limit AFTER posting the link to their website.
  const clientLimit = await checkClientLimit(user.id);
  if (!clientLimit.allowed) {
    return NextResponse.json(
      {
        error: "Client limit reached",
        message: `You've reached your limit of ${clientLimit.limit} clients. Upgrade to add more.`,
        showUpgrade: true,
      },
      { status: 403 }
    );
  }

  // Insert intake link using admin client (token generated by DB default)
  const admin = createAdminClient();
  const insertPayload: {
    user_id: string;
    is_permanent: boolean;
    expires_at?: string;
  } = {
    user_id: user.id,
    is_permanent: permanent,
  };
  if (permanent) insertPayload.expires_at = PERMANENT_LINK_EXPIRY_ISO;

  const { data, error } = await admin
    .from("intake_links")
    .insert(insertPayload)
    .select("token, expires_at, is_permanent")
    .single();

  if (error) {
    console.error("Error creating intake link:", error);
    return NextResponse.json(
      { error: "Failed to generate questionnaire link" },
      { status: 500 }
    );
  }

  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://retirementexpert.ai";
  const url = `${baseUrl}/intake/${data.token}`;

  return NextResponse.json(
    {
      token: data.token,
      url,
      // For permanent links, expires_at is just a "100 years from now"
      // sentinel — the UI should suppress the expiry hint when permanent.
      expires_at: data.expires_at,
      is_permanent: data.is_permanent,
    },
    { status: 201 }
  );
}
