import { createClient } from "@supabase/supabase-js";
import { config } from "dotenv"; import { resolve } from "path";
import { runGrowthSimulation, createSimulationInput } from "../lib/calculations";
import type { Client } from "../lib/types/client";
config({ path: resolve(process.cwd(), ".env.local") });
const admin = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { autoRefreshToken: false, persistSession: false } });
const $=(c:number)=>"$"+(c/100).toLocaleString('en-US',{maximumFractionDigits:0});
const sum=(a:any[],k:string)=>a.reduce((s,y)=>s+(Number(y[k])||0),0);
(async()=>{
  const {data}=await admin.from("clients").select("*").eq("id","cb7a54be-0098-4a87-b6da-e5b6b009a72c").single();
  const base1m={...data, traditional_ira:100000000, qualified_account_value:100000000} as Client;
  const hr=((data as any).heir_tax_rate??40)/100;
  const bl=runGrowthSimulation(createSimulationInput(base1m,null)).baseline;
  const lb=bl[bl.length-1] as any; const baseNet=lb.netWorth-Math.round(lb.traditionalBalance*hr);
  console.log("=== $1M qualified account, 24% bonus=$240K ===");
  console.log("Baseline: gross",$(lb.netWorth),"| trad left",$(lb.traditionalBalance),"| net to heirs",$(baseNet),"\n");
  const run=(type:string,ceil:number,label:string)=>{
    const cc={...base1m, conversion_type:type, max_tax_rate:ceil, tax_rate:ceil, federal_bracket:String(ceil)} as any;
    const r=runGrowthSimulation(createSimulationInput(cc,null));
    const f=r.formula as any[]; const lf=f[f.length-1];
    const net=lf.netWorth-Math.round(lf.traditionalBalance*hr);
    const conv=sum(f,'conversionAmount'), convTax=sum(f,'federalTaxOnConversions')+sum(f,'stateTaxOnConversions');
    const c26=f.find(y=>y.year===2026)?.conversionAmount||0, c27=f.find(y=>y.year===2027)?.conversionAmount||0;
    console.log(`${label}`);
    console.log(`   gross legacy ${$(lf.netWorth)} | net to heirs ${$(net)} | wins by ${$(net-baseNet)}`);
    console.log(`   converted ${$(conv)} (tax ${$(convTax)}) | trad left ${$(lf.traditionalBalance)} | wage-yr conv: 2026 ${$(c26)}, 2027 ${$(c27)}\n`);
  };
  run('fixed_amount',24,"FIXED $150k/yr (current, ignores ceiling)");
  run('optimized_amount',24,"OPTIMIZED @ 24% ceiling");
  run('optimized_amount',32,"OPTIMIZED @ 32% ceiling");
  run('optimized_amount',35,"OPTIMIZED @ 35% ceiling");
})();
